language: python
dist: xenial
python:
- '3.7'

before_install:
- sudo apt-get install jq
install:
- source environment
- make requirements
- make requirements-dev
- make build
script:
- source environment
- make test
